### ISSUE TITLE
Privacy and Cookie Policy

### ISSUE THREAD

**Issue by ChristopherJamesMorris** [nhsconnect/gpconnect-appointment-checker#105] opened 2021-01-15 10:27 UTC
To include a privacy and cookie policy which is specific to the Appointment Checker.

**Comment by jonnyry** [comment] 2021-01-26 15:06
Duplicate of https://github.com/nhsconnect/gpconnect-appointment-checker/issues/73

**Comment by jonnyry** [comment] 2021-01-29 14:05
Fixed.

**Closed by jonnyry** 2021-01-29 14:05 UTC
